name: Inference

on:
  schedule:
    # Run daily at midnight UTC
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:

  update:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "hopsworks[python]" yfinance pandas tensorflow joblib matplotlib scikit-learn

      - name: Run inference script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}  # Replace with your actual secret name
        run: python inference.py

      - name: Commit and Push Plots
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *
          git commit -m "Add updated plots from inference"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
